# Generated by Django 3.0.5 on 2020-04-18 12:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_img', models.ImageField(upload_to='home/img/')),
                ('date_time', models.DateTimeField(default=datetime.datetime(2020, 4, 18, 12, 11, 42, 558049, tzinfo=utc))),
            ],
        ),
    ]
