# Generated by Django 3.0.5 on 2020-04-19 04:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200418_1743'),
    ]

    operations = [
        migrations.CreateModel(
            name='Centre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('centre_name', models.CharField(default='', max_length=50)),
                ('date_time', models.DateTimeField(default=datetime.datetime(2020, 4, 19, 4, 48, 1, 412000, tzinfo=utc))),
            ],
        ),
        migrations.AlterField(
            model_name='event',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 19, 4, 48, 1, 412000, tzinfo=utc)),
        ),
    ]
