# Generated by Django 3.0.5 on 2020-04-19 04:50

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200419_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='centre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.Centre'),
        ),
        migrations.AlterField(
            model_name='centre',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 19, 4, 50, 13, 774570, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='event',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 19, 4, 50, 13, 774570, tzinfo=utc)),
        ),
    ]
