# Generated by Django 3.0.5 on 2020-04-19 05:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200419_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centre',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 19, 5, 8, 36, 919693, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='event',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 19, 5, 8, 36, 919693, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_img',
            field=models.ImageField(upload_to='home/event/'),
        ),
    ]
