# Generated by Django 3.0.5 on 2020-04-19 05:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20200419_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='centre',
            name='centre_img',
            field=models.ImageField(blank=True, upload_to='home/centre/'),
        ),
        migrations.AlterField(
            model_name='centre',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 19, 5, 9, 26, 585119, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='event',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 19, 5, 9, 26, 589113, tzinfo=utc)),
        ),
    ]
