# Generated by Django 3.0.5 on 2020-04-19 05:12

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20200419_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centre',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 19, 5, 12, 18, 28093, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='event',
            name='centre',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='home.Centre'),
        ),
        migrations.AlterField(
            model_name='event',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 19, 5, 12, 18, 28093, tzinfo=utc)),
        ),
    ]
