# Generated by Django 3.0.5 on 2020-04-19 15:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_centre_centre_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centre',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 19, 21, 29, 21, 345380)),
        ),
        migrations.AlterField(
            model_name='event',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 19, 21, 29, 21, 345380)),
        ),
    ]
