# Generated by Django 3.0.5 on 2020-04-23 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20200420_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='centre',
            name='centre_location',
            field=models.CharField(default='', max_length=100),
        ),
    ]
